services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  web:
    build: .
    command: python run_web.py
    volumes:
      - ./outputs:/app/outputs
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Optimized batch processing workers for local machine
  batch-worker:
    build: .
    command: rq worker --url redis://redis:6379/0 batch_processing
    volumes:
      - ./outputs:/app/outputs
      - ./uploads:/app/uploads
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 4  # Reduced from 12 to 4 for local machine
      resources:
        limits:
          memory: 1.5G
          cpus: '0.5'
        reservations:
          memory: 768M
          cpus: '0.25'

  # Merge processing workers (for final file generation)
  merge-worker:
    build: .
    command: rq worker --url redis://redis:6379/0 merge_processing
    volumes:
      - ./outputs:/app/outputs
      - ./uploads:/app/uploads
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 2  # Reduced from 4 to 2 for local machine
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Legacy worker for backward compatibility
  worker:
    build: .
    command: rq worker --url redis://redis:6379/0
    volumes:
      - ./outputs:/app/outputs
      - ./uploads:/app/uploads
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 1  # Reduced from 2 to 1 for local machine
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
